import streamlit
streamlit.title('My Parents New Healthy Diner')
streamlit.header('Breakfast Menu🥣')
streamlit.text('Idly')
streamlit.text('Dosa')
streamlit.text('Vada')
streamlit.text('Poori')
streamlit.header('Lunch Menu')
streamlit.text('🍛 Curry Rice')
streamlit.text('🍙 Rice Ball')
streamlit.text('🍚 Cooked Rice')
streamlit.header('🍌🥭 Build Your Own Fruit Smoothie 🥝🍇')
streamlit.text('🍍 Pineapple 🥭 Mango')
streamlit.text('🍎 Red Apple 🍏 Green Apple')
streamlit.text('🍐 Pear 🍑 Peach')
streamlit.text('🍒 Cherries 🍓 Strawberry')
streamlit.text('🫐 Blueberries 🥝 Kiwi Fruit')
